# ansible-playbook playbook.yml -u <username> --tags system,app -K
- name: 通用服务器管理
  tags: packages
  hosts: 127.0.0.1
  become: true
  gather_facts: false
  environment:
    http_proxy: "http://127.0.0.1:7890"
    https_proxy: "http://127.0.0.1:7890"
    socks5_proxy: "socks5://127.0.0.1:7890"
  vars_files:
    - vars/main.yml
    - vars/deb.yml
    - vars/rpm.yml
    - vars/apps.yml

  tasks:
    - name: Ping
      tags: "always"
      ansible.builtin.ping:

    - name: Gather facts
      tags: "always"
      ansible.builtin.gather_facts:

    - name: 系统基础配置
      tags: "system"
      ansible.builtin.include_tasks: tasks/install_packages.yml

    - name: 安装Github上的软件
      tags: "apps"
      block:
        - name: Gather the package facts
          ansible.builtin.package_facts:
            manager: auto

        - name: Process Github installations
          ansible.builtin.include_tasks: tasks/install_logic.yml
          loop: "{{ apps }}"
          loop_control:
            loop_var: app
