# ansible-playbook playbook.yml -u <username>
- name: 通用服务器管理
  tags: packages
  hosts: 127.0.0.1
  become: true
  vars:
    required_packages:
      - curl
      - zip
      - unzip
      - tar
      - gcc
      - clang
      - llvm
      - build-essential
      - openssl
      - shfmt
      - libclang-dev
      - libssl-dev
      - libopencv-dev
  tasks:
    - name: Ping
      ansible.builtin.ping:

    - name: 更新 apt 缓存
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: 安装列表中的包
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: "{{ required_packages }}"

- name: 安装github上指定版本的包
  tags: apps
  hosts: 127.0.0.1
  become: true
  gather_facts: true
  environment:
    http_proxy: "http://127.0.0.1:7890"
    https_proxy: "http://127.0.0.1:7890"
    socks5_proxy: "socks5://127.0.0.1:7890"
  vars_files:
    - vars/main.yml
  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Process Github Deb installations
      ansible.builtin.include_tasks: tasks/install_logic.yml
      loop: "{{ softwares }}"
      loop_control:
        loop_var: app
