# ansible-playbook site.yml -u <username> --tags system,github,flathub,python,npm,unfree --become -K
# ansible-playbook site.yml -u <username> --tags admin --become -K
# ansible-playbook site.yml -u <username> --tags non-admin
- name: 通用软件管理
  hosts: 127.0.0.1
  gather_facts: false
  environment:
    http_proxy: "http://127.0.0.1:7890"
    https_proxy: "http://127.0.0.1:7890"
    socks5_proxy: "socks5://127.0.0.1:7890"

  pre_tasks:
    - name: Ping
      tags: "always"
      ansible.builtin.ping:

    - name: Gather facts
      tags: "always"
      ansible.builtin.setup:
        gather_subset: min

  roles:
    - role: system
      tags: ["system", "admin"]

    - role: github
      tags: ["github", "admin"]

    - role: flathub
      tags: ["flathub", "non-admin"]

    - role: python
      tags: ["python", "non-admin"]

    - role: npm
      tags: ["npm", "non-admin"]

    - role: unfree
      tags: ["unfree", "admin"]
