- name: Load variables
  ansible.builtin.include_vars: vars/main.yml

- name: Make Flathub source is ready
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Flathub applications
  community.general.flatpak:
    name: "{{ item.name }}"
    state: "{{ item.state | default('latest') }}"
    method: system
  loop: "{{ flathub_apps }}"
  loop_control:
    label: "正在处理{{ item.name }}: {{ item.description }}"
