flathub_apps:
  - name: com.github.tchx84.Flatseal
    description: Flatsea
    state: latest # 可选值latest, present
  - name: com.tencent.WeChat
    description: 微信
  - name: com.redis.RedisInsight
    description: redis insight
  - name: org.nickvision.tubeconverter
    description: yt-dlp frontend (Parabolic)
